xxl:
  job:
    accessToken:
    admin:
      addresses: http://localhost:19999/wethink-job-admin
    executor:
      appname: xxljob-demo
      address:
      ip:
      port: 17060
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30